# Generated by Django 3.2.23 on 2024-01-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volkswagen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='clients1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('num', models.IntegerField()),
                ('model', models.CharField(max_length=45)),
            ],
        ),
    ]
